// Initial seed data for Belgrade locations
import { Category, Location } from '@/types';

export const categories: Omit<Category, 'locations'>[] = [
  {
    id: 'cat-landmarks',
    name: 'Landmarks',
    slug: 'landmarks',
    icon: 'landmark',
    color: '#D4A574',
    description: 'Historic landmarks and monuments',
  },
  {
    id: 'cat-restaurants',
    name: 'Restaurants',
    slug: 'restaurants',
    icon: 'restaurant',
    color: '#E07B54',
    description: 'Traditional and modern cuisine',
  },
  {
    id: 'cat-hotels',
    name: 'Hotels',
    slug: 'hotels',
    icon: 'hotel',
    color: '#6B8E7B',
    description: 'Accommodation for every budget',
  },
  {
    id: 'cat-nightlife',
    name: 'Nightlife',
    slug: 'nightlife',
    icon: 'nightlife',
    color: '#7B6B9E',
    description: 'Bars, clubs, and entertainment',
  },
  {
    id: 'cat-attractions',
    name: 'Attractions',
    slug: 'attractions',
    icon: 'attraction',
    color: '#4A90A4',
    description: 'Museums, galleries, and activities',
  },
  {
    id: 'cat-nature',
    name: 'Nature & Parks',
    slug: 'nature',
    icon: 'nature',
    color: '#6B9E6B',
    description: 'Parks, rivers, and outdoor spaces',
  },
];

export const locations: Omit<Location, 'category'>[] = [
  // === LANDMARKS ===
  {
    id: 'loc-kalemegdan',
    name: 'Kalemegdan Fortress',
    slug: 'kalemegdan-fortress',
    description: 'Belgrade\'s ancient fortress overlooking the confluence of the Sava and Danube rivers. One of the most beautiful and largest fortress complexes in Europe, with a history spanning over 2,000 years. The fortress contains the Victor Monument, Military Museum, and stunning views of New Belgrade.',
    shortDesc: 'Ancient fortress with stunning river views',
    address: 'Kalemegdan bb, Stari Grad, Belgrade',
    latitude: 44.8224,
    longitude: 20.4512,
    rating: 4.8,
    priceLevel: 0,
    phone: '+381 11 334 4212',
    website: 'https://www.beograd.rs',
    featured: true,
    verified: true,
    categoryId: 'cat-landmarks',
  },
  {
    id: 'loc-saint-sava',
    name: 'Saint Sava Temple',
    slug: 'saint-sava-temple',
    description: 'One of the largest Orthodox churches in the world and the largest church building in the Balkans. The magnificent cathedral dominates Belgrade\'s skyline and can hold up to 10,000 people. The interior features stunning gold mosaics and Byzantine architecture.',
    shortDesc: 'Largest Orthodox church in the Balkans',
    address: 'Krušedolska 2a, Vračar, Belgrade',
    latitude: 44.7983,
    longitude: 20.4686,
    rating: 4.9,
    priceLevel: 0,
    phone: '+381 11 344 6806',
    website: 'https://www.hramsvetogsave.rs',
    featured: true,
    verified: true,
    categoryId: 'cat-landmarks',
  },
  {
    id: 'loc-avalatoranj',
    name: 'Avala Tower',
    slug: 'avala-tower',
    description: 'The iconic 205-meter tall TV tower on Avala mountain, originally built in 1965 and reconstructed in 2010. Features an observation deck at 119 meters with panoramic views of Belgrade and surrounding areas. A symbol of modern Serbian architecture.',
    shortDesc: 'Iconic TV tower with panoramic views',
    address: 'Avala Mountain, Belgrade',
    latitude: 44.6894,
    longitude: 20.5147,
    rating: 4.6,
    priceLevel: 1,
    phone: '+381 11 328 7111',
    website: 'https://www.toranj.rs',
    featured: true,
    verified: true,
    categoryId: 'cat-landmarks',
  },
  {
    id: 'loc-skadarlija',
    name: 'Skadarlija Street',
    slug: 'skadarlija-street',
    description: 'Belgrade\'s Bohemian quarter, a historic cobblestone street lined with traditional restaurants, live music, and artistic heritage. Known as the "Montmartre of Belgrade," this pedestrian zone has been the heart of the city\'s cultural life since the 19th century.',
    shortDesc: 'Historic Bohemian quarter with traditional restaurants',
    address: 'Skadarska ulica, Stari Grad, Belgrade',
    latitude: 44.8193,
    longitude: 20.4628,
    rating: 4.5,
    priceLevel: 2,
    featured: true,
    verified: true,
    categoryId: 'cat-landmarks',
  },

  // === NATURE & PARKS ===
  {
    id: 'loc-ada-ciganlija',
    name: 'Ada Ciganlija',
    slug: 'ada-ciganlija',
    description: 'Belgrade\'s favorite summer destination, a river island turned peninsula with a 4km long pebble beach along the Sava River. Features numerous sports facilities, bike paths, cafes, and the famous "Košarkaški klub" beach bars. Perfect for swimming, cycling, and outdoor activities.',
    shortDesc: 'Belgrade\'s summer paradise with beaches and sports',
    address: 'Ada Ciganlija, Čukarica, Belgrade',
    latitude: 44.7833,
    longitude: 20.4000,
    rating: 4.7,
    priceLevel: 1,
    featured: true,
    verified: true,
    categoryId: 'cat-nature',
  },
  {
    id: 'loc-kosutnjak',
    name: 'Košutnjak Forest',
    slug: 'kosutnjak-forest',
    description: 'A sprawling forest park covering over 300 hectares on the outskirts of Belgrade. Popular for hiking, cycling, and picnics. Contains the Košutnjak film city, numerous restaurants, and the Hajducka Cesma spring. A peaceful escape from the urban bustle.',
    shortDesc: 'Vast forest park for hiking and recreation',
    address: 'Košutnjak, Čukarica, Belgrade',
    latitude: 44.7556,
    longitude: 20.4203,
    rating: 4.5,
    priceLevel: 0,
    verified: true,
    categoryId: 'cat-nature',
  },
  {
    id: 'loc-topcider',
    name: 'Topčider Park',
    slug: 'topcider-park',
    description: 'One of Belgrade\'s oldest parks, established in the 1830s as a royal hunting ground. Features the historic Konak of Prince Miloš, the oldest preserved building in Belgrade, and the famous restaurant "Mladost." Beautiful walking paths and mature trees.',
    shortDesc: 'Historic royal park with Prince Miloš\'s residence',
    address: 'Topčider, Savski Venac, Belgrade',
    latitude: 44.7708,
    longitude: 20.4511,
    rating: 4.4,
    priceLevel: 0,
    verified: true,
    categoryId: 'cat-nature',
  },

  // === RESTAURANTS ===
  {
    id: 'loc-znakpitanja',
    name: '? Restaurant',
    slug: 'znak-pitanja-restaurant',
    description: 'The oldest restaurant in Belgrade (est. 1823), located right next to Kalemegdan Fortress. Famous for traditional Serbian cuisine and the question mark sign that gave it its name. A must-visit for authentic Balkan dining experience in a historic setting.',
    shortDesc: 'Oldest restaurant in Belgrade with traditional cuisine',
    address: 'Kralja Petra I 6, Stari Grad, Belgrade',
    latitude: 44.8215,
    longitude: 20.4538,
    rating: 4.6,
    priceLevel: 2,
    phone: '+381 11 635 422',
    featured: true,
    verified: true,
    categoryId: 'cat-restaurants',
  },
  {
    id: 'loc-dva-jelena',
    name: 'Dva Jelena',
    slug: 'dva-jelena-restaurant',
    description: 'A historic restaurant in the heart of Skadarlija since 1832. Famous for traditional Serbian cuisine, live tamburitza music, and authentic atmosphere. The name means "Two Deer" and the restaurant has hosted countless celebrities and dignitaries.',
    shortDesc: 'Historic Skadarlija restaurant with live music',
    address: 'Skadarska 32, Stari Grad, Belgrade',
    latitude: 44.8189,
    longitude: 20.4623,
    rating: 4.5,
    priceLevel: 2,
    phone: '+381 11 324 3612',
    featured: true,
    verified: true,
    categoryId: 'cat-restaurants',
  },
  {
    id: 'loc-saran',
    name: 'Šaran Restaurant',
    slug: 'saran-restaurant',
    description: 'Legendary fish restaurant on the banks of the Danube in Zemun. Famous for its fresh fish dishes, especially the Danube carp and perch. The outdoor terrace offers stunning views of the river and the Great War Island.',
    shortDesc: 'Legendary fish restaurant on the Danube',
    address: 'Kej Oslobođenja 53, Zemun, Belgrade',
    latitude: 44.8433,
    longitude: 20.4067,
    rating: 4.7,
    priceLevel: 3,
    phone: '+381 11 328 4120',
    featured: true,
    verified: true,
    categoryId: 'cat-restaurants',
  },
  {
    id: 'loc-homa',
    name: 'Homa Restaurant',
    slug: 'homa-restaurant',
    description: 'Modern Mediterranean restaurant in the Dorćol neighborhood. Known for creative fusion cuisine combining Serbian and international flavors. Elegant interior, professional service, and carefully curated wine list make it perfect for special occasions.',
    shortDesc: 'Modern Mediterranean cuisine in Dorćol',
    address: 'Simina 21, Stari Grad, Belgrade',
    latitude: 44.8231,
    longitude: 20.4589,
    rating: 4.4,
    priceLevel: 3,
    phone: '+381 11 323 1234',
    verified: true,
    categoryId: 'cat-restaurants',
  },

  // === NIGHTLIFE ===
  {
    id: 'loc-splavovi',
    name: 'Danube & Sava Splavovi',
    slug: 'splavovi-river-clubs',
    description: 'Belgrade\'s famous floating river clubs (splavovi) lining both the Sava and Danube rivers. Each barge offers a unique atmosphere - from laid-back lounges to high-energy dance clubs. The heart of Belgrade\'s legendary nightlife scene.',
    shortDesc: 'Famous floating river clubs - Belgrade\'s nightlife heart',
    address: 'Kej oslobođenja, Belgrade',
    latitude: 44.8150,
    longitude: 20.4400,
    rating: 4.6,
    priceLevel: 2,
    featured: true,
    verified: true,
    categoryId: 'cat-nightlife',
  },
  {
    id: 'loc-strahinjica-bana',
    name: 'Strahinjića Bana Street',
    slug: 'strahinjica-bana-street',
    description: 'Known as "Silicone Valley" by locals, this narrow street in Dorćol is packed with trendy bars, cafes, and restaurants. The epicenter of Belgrade\'s hipster scene with a vibrant atmosphere day and night. Perfect for bar-hopping.',
    shortDesc: 'Trendy bar street in Dorćol - the hipster hub',
    address: 'Strahinjića Bana, Stari Grad, Belgrade',
    latitude: 44.8197,
    longitude: 20.4608,
    rating: 4.4,
    priceLevel: 2,
    verified: true,
    categoryId: 'cat-nightlife',
  },
  {
    id: 'loc-knez-mihailova',
    name: 'Knez Mihailova Street',
    slug: 'knez-mihailova-street',
    description: 'Belgrade\'s main pedestrian street, connecting Kalemegdan to Republic Square. Lined with 19th-century buildings, cafes, shops, and street performers. One of the most beautiful and liveliest streets in the Balkans, perfect for strolling.',
    shortDesc: 'Main pedestrian street with cafes and shops',
    address: 'Knez Mihailova, Stari Grad, Belgrade',
    latitude: 44.8175,
    longitude: 20.4569,
    rating: 4.6,
    priceLevel: 1,
    featured: true,
    verified: true,
    categoryId: 'cat-attractions',
  },

  // === ATTRACTIONS ===
  {
    id: 'loc-republic-square',
    name: 'Republic Square',
    slug: 'republic-square',
    description: 'Belgrade\'s central square featuring the iconic Statue of Prince Mihailo on horseback, the National Museum, and the National Theatre. The square is the heart of the city and a popular meeting point for locals and tourists alike.',
    shortDesc: 'Central square with Prince Mihailo statue',
    address: 'Trg Republike, Stari Grad, Belgrade',
    latitude: 44.8165,
    longitude: 20.4603,
    rating: 4.5,
    priceLevel: 0,
    verified: true,
    categoryId: 'cat-attractions',
  },
  {
    id: 'loc-national-museum',
    name: 'National Museum',
    slug: 'national-museum',
    description: 'The largest and oldest museum in Serbia, housing over 400,000 exhibits including archaeological finds, medieval art, and modern paintings. Features works by Picasso, Renoir, and Serbian masters. Recently renovated to its former glory.',
    shortDesc: 'Largest museum in Serbia with world-class collections',
    address: 'Trg Republike 1a, Stari Grad, Belgrade',
    latitude: 44.8158,
    longitude: 20.4600,
    rating: 4.7,
    priceLevel: 1,
    phone: '+381 11 334 3800',
    website: 'https://www.narodnimuzej.rs',
    verified: true,
    categoryId: 'cat-attractions',
  },
  {
    id: 'loc-nikola-tesla-museum',
    name: 'Nikola Tesla Museum',
    slug: 'nikola-tesla-museum',
    description: 'Dedicated to the life and work of Serbian-American inventor Nikola Tesla. Houses Tesla\'s original documents, models of his inventions, and interactive exhibits. A must-visit for science enthusiasts and Tesla admirers from around the world.',
    shortDesc: 'Dedicated to genius inventor Nikola Tesla',
    address: 'Krunska 51, Vračar, Belgrade',
    latitude: 44.8033,
    longitude: 20.4700,
    rating: 4.8,
    priceLevel: 1,
    phone: '+381 11 343 6646',
    website: 'https://www.tesla-museum.org',
    featured: true,
    verified: true,
    categoryId: 'cat-attractions',
  },
  {
    id: 'loc-zemun',
    name: 'Zemun Old Town',
    slug: 'zemun-old-town',
    description: 'A charming historic neighborhood that was once a separate town under Austro-Hungarian rule. Features cobblestone streets, baroque architecture, the iconic Gardoš Tower, and the beautiful Danube promenade. A different side of Belgrade.',
    shortDesc: 'Charming Austro-Hungarian old town with Gardoš Tower',
    address: 'Zemun, Belgrade',
    latitude: 44.8428,
    longitude: 20.4056,
    rating: 4.6,
    priceLevel: 1,
    featured: true,
    verified: true,
    categoryId: 'cat-attractions',
  },

  // === HOTELS ===
  {
    id: 'loc-square-nine',
    name: 'Square Nine Hotel',
    slug: 'square-nine-hotel',
    description: 'Belgrade\'s most prestigious 5-star hotel, located in a beautifully restored 1920s building near Kalemegdan. Features world-class amenities, a spa, and the renowned The Square restaurant. Winner of multiple international awards.',
    shortDesc: 'Luxury 5-star hotel near Kalemegdan',
    address: 'Studentski trg 9, Stari Grad, Belgrade',
    latitude: 44.8128,
    longitude: 20.4550,
    rating: 4.8,
    priceLevel: 4,
    phone: '+381 11 333 3000',
    website: 'https://www.squarenine.rs',
    featured: true,
    verified: true,
    categoryId: 'cat-hotels',
  },
  {
    id: 'loc-moscow-hotel',
    name: 'Hotel Moskva',
    slug: 'hotel-moskva',
    description: 'A historic 4-star hotel and Belgrade landmark since 1908. Famous for its Secessionist architecture and the legendary Moskva Snopitza cake. Located opposite the Old Palace, steps from Terazije Square.',
    shortDesc: 'Historic Secessionist hotel since 1908',
    address: 'Terazije 20, Stari Grad, Belgrade',
    latitude: 44.8108,
    longitude: 20.4606,
    rating: 4.5,
    priceLevel: 3,
    phone: '+381 11 330 1700',
    website: 'https://www.hotelmoskva.rs',
    featured: true,
    verified: true,
    categoryId: 'cat-hotels',
  },
  {
    id: 'loc-metropol-palace',
    name: 'Metropol Palace Hotel',
    slug: 'metropol-palace-hotel',
    description: 'A landmark 5-star hotel overlooking Tašmajdan Park. Originally opened in 1957, fully renovated in 2012. Features the famous Ruby bar, an indoor pool, and stunning city views. A blend of mid-century elegance and modern luxury.',
    shortDesc: 'Elegant 5-star hotel with city views',
    address: 'Bulevar kralja Aleksandra 69, Vračar, Belgrade',
    latitude: 44.8081,
    longitude: 20.4694,
    rating: 4.6,
    priceLevel: 4,
    phone: '+381 11 333 5500',
    website: 'https://www.metropolpalace.com',
    verified: true,
    categoryId: 'cat-hotels',
  },
  {
    id: 'loc-majdan-art',
    name: 'Hotel Majdan',
    slug: 'hotel-majdan',
    description: 'A boutique 4-star hotel near Slavija Square with contemporary design and excellent value. Perfect for business travelers and tourists seeking comfort without the luxury price tag. Walking distance to major attractions.',
    shortDesc: 'Boutique hotel with great value near city center',
    address: 'Resavska 30b, Vračar, Belgrade',
    latitude: 44.7992,
    longitude: 20.4656,
    rating: 4.3,
    priceLevel: 2,
    phone: '+381 11 334 0200',
    website: 'https://www.hotelmajdan.rs',
    verified: true,
    categoryId: 'cat-hotels',
  },
];
