import { NextResponse } from 'next/server'
import { staticLocations } from '@/lib/static-data'

// Generate sitemap.xml for SEO
export async function GET() {
  const baseUrl = 'https://belgrade.pro'
  
  // Static pages
  const staticPages = [
    { loc: baseUrl, changefreq: 'daily', priority: 1.0 },
    { loc: `${baseUrl}/restorani`, changefreq: 'weekly', priority: 0.9 },
    { loc: `${baseUrl}/hoteli`, changefreq: 'weekly', priority: 0.9 },
    { loc: `${baseUrl}/nocni-zivot`, changefreq: 'weekly', priority: 0.9 },
    { loc: `${baseUrl}/znamenitosti`, changefreq: 'weekly', priority: 0.8 },
  ]
  
  // Location pages
  const locationPages = staticLocations.map(loc => ({
    loc: `${baseUrl}/lokacija/${loc.slug}`,
    changefreq: 'weekly' as const,
    priority: loc.featured ? 0.8 : 0.6,
    lastmod: loc.updatedAt,
  }))
  
  // SEO topic pages (generated by cron)
  const seoKeywords = [
    'najbolji-restorani-beograd',
    'restorani-skadarlija',
    'srpska-kuhinja-beograd',
    'hoteli-beograd-centar',
    'nocni-zivot-beograd',
    'splavovi-beograd',
    'kalemegdan-tvrdjava',
    'hram-svetog-save',
    'ada-ciganlija',
    'muzeji-beograd',
  ]
  
  const seoPages = seoKeywords.map(slug => ({
    loc: `${baseUrl}/seo/${slug}`,
    changefreq: 'monthly' as const,
    priority: 0.7,
  }))
  
  const allPages = [...staticPages, ...locationPages, ...seoPages]
  
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${allPages.map(page => `  <url>
    <loc>${page.loc}</loc>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
    ${page.lastmod ? `<lastmod>${page.lastmod.split('T')[0]}</lastmod>` : ''}
  </url>`).join('\n')}
</urlset>`

  return new NextResponse(sitemap, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  })
}
